server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url : jdbc:mysql://127.0.0.1:3306/shilianglsql
    username : root
    password : 0709
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true